spring:
  application:
    name: projectHeritage
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/PROJECTHR
    username: HRDBA
    password: hrdba9999
    mapper-locations: classpath:/mapper/**/*.xml
    hikari:
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 24000
      maximum-pool-size: 20
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            user-name-attribute: id
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kako.com/v2/user/me
        registration:
          kakao:
            client-name: kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/auth/kakao/loginProcess
            client-id: ec12629b9ffa112304759b21d935774d
            client-secret: yrsreMlE0ppK88rFVd3rcjvDpWZoNLF7
            client-authentication-method: POST
            scope: profile_nickname,account_email



# ===================================================================
# properties
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework: INFO
    root: INFO
# ===================================================================

