spring:
  application:
    name: projectHeritage
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/PROJECTHR?serverTimezone=UTC
    password: HRDBA
    username: HRDBA9999
logging:
  config: classpath:log4j2/log4j2.xml
  level:
    root: DEBUG
